### ISSUE TITLE
Convergence diagnostics

### ISSUE THREAD

**Issue by FrankD** [chrism0dwk/covid19uk#5]
@chrism0dwk, I was thinking of implementing some convergence diagnostics for your MCMC; is this useful? I'm thinking effective sample size and maybe Gelman-Rubin R-hat.

https://arxiv.org/pdf/1909.11827.pdf

**Comment by chrism0dwk** [comment]
Frank, and ESS implementation would be awesome, thanks!  BGR optional, but ESS might be useful in-chain as well as post-hoc.

**Comment by FrankD** [comment]
Disappointingly (for my coding enjoyment), it turns out that this is already implemented in Tensorflow probability.

I added calculation of the ESS to the end of the `mcmc.py` script. Pull request #7 (but it's literally one line).
